In [2]:
import pandas as pd
import numpy as np
import matplotlib as pl
%matplotlib inline

from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier  
from sklearn.tree import DecisionTreeRegressor 
from sklearn.model_selection import cross_val_score

In [24]:
data = pd.read_csv("bikes_train.csv")

In [26]:
data["datetime"] = pd.to_datetime(data["datetime"])
data["dayofweek"] = data["datetime"].dt.dayofweek      #The day of the week with Monday=0, Sunday=6
data["year"] = data["datetime"].dt.year
data["month"] = data["datetime"].dt.month
data["day"] = data["datetime"].dt.day
data["hour"] = data["datetime"].dt.hour

In [27]:
y = data["count"]
features = ["season","holiday","workingday","weather","temp","atemp","humidity","windspeed","dayofweek","year","month","day","hour"]
X = data[features]

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
parameters = {'max_depth': range(1, 11),
              'min_samples_split': range(2, 21), 'min_samples_leaf': range(1, 21)}
tree = DecisionTreeRegressor()

In [10]:
regressor = GridSearchCV(estimator = tree, param_grid = parameters)

In [11]:
regressor.fit(X = X_train, y=y_train)

GridSearchCV(cv=None, error_score='raise',
       estimator=DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best'),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'max_depth': range(1, 11), 'min_samples_split': range(2, 21), 'min_samples_leaf': range(1, 21)},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [12]:
predicted = regressor.predict(X_test)

In [13]:
wyniki = pd.DataFrame({"y_true":y_test,"y_pred":predicted}, index = y_test.index)

In [15]:
def rmsle(y_pred, y_true) :
    assert len(y_true) == len(y_pred)
    return np.sqrt(np.mean((np.log(1+y_pred) - np.log(1+y_true))**2))

In [39]:
rmsle(y_pred=predicted, y_true=y_test)

0.383604945875327

In [40]:
test = pd.read_csv("https://storage.googleapis.com/kaggle-competitions-data/kaggle/3948/test.csv?GoogleAccessId=web-data@kaggle-161607.iam.gserviceaccount.com&Expires=1528195692&Signature=j5Y0p3gSNPzLQ%2FlUG20AHX8D5YYcXqTJx%2FH6GoUoGzI1ECywxEhvRGlAjwe4V4B73NYHXLY0sYZPpSymKphoPF8as4eRNDrK%2BRu6gTC1mfYDRZoMp7%2F5fppYcQiWHtXJzTT3tZtt0q6SQZXrE5%2BHIFl2TNBnB7yTXrpG1Xif5upFEH6Ja7OLCCsmGlOmOhlI8RNm3uGMAgJhBGrnLojST%2FPCi4TeStZ2QqI4zYA3D4mGHSMGQzLw47tIP9CfOR1I14H53vc7MSLmzxMO7uhSd5h2uqVuDXzj%2B%2Br8HJjCjWpRve1dqhAWLrcW26SYZueG%2FKXXotm4UWvx6MD%2BCJzryg%3D%3D")

In [41]:
test["datetime"] = pd.to_datetime(test["datetime"])
test["dayofweek"] = test["datetime"].dt.dayofweek      #The day of the week with Monday=0, Sunday=6
test["year"] = test["datetime"].dt.year
test["month"] = test["datetime"].dt.month
test["day"] = test["datetime"].dt.day
test["hour"] = test["datetime"].dt.hour

In [48]:
kaggle_test = test[["season","holiday","workingday","weather","temp","atemp","humidity","windspeed","dayofweek","year","month","day","hour"]]

In [49]:
regressor.fit(X, y)

GridSearchCV(cv=None, error_score='raise',
       estimator=DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best'),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'max_depth': range(1, 11), 'min_samples_split': range(2, 21), 'min_samples_leaf': range(1, 21)},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [54]:
test["count"] = regressor.predict(kaggle_test)

In [56]:
test[["datetime", "count"]]

                datetime       count
0    2011-01-20 00:00:00   11.375000
1    2011-01-20 01:00:00   10.500000
2    2011-01-20 02:00:00    7.400000
3    2011-01-20 03:00:00    2.470588
4    2011-01-20 04:00:00    2.470588
5    2011-01-20 05:00:00    7.625000
6    2011-01-20 06:00:00   37.571429
7    2011-01-20 07:00:00  128.678571
8    2011-01-20 08:00:00  128.678571
9    2011-01-20 09:00:00  128.678571
10   2011-01-20 10:00:00   61.888889
11   2011-01-20 11:00:00   61.888889
12   2011-01-20 12:00:00   61.888889
13   2011-01-20 13:00:00   61.888889
14   2011-01-20 14:00:00   61.888889
15   2011-01-20 15:00:00   61.888889
16   2011-01-20 16:00:00   61.888889
17   2011-01-20 17:00:00  179.142857
18   2011-01-20 18:00:00  179.142857
19   2011-01-20 19:00:00  103.555556
20   2011-01-20 20:00:00   69.391304
21   2011-01-20 21:00:00   44.750000
22   2011-01-20 22:00:00   40.909091
23   2011-01-20 23:00:00   16.625000
24   2011-01-21 00:00:00   11.375000
25   2011-01-21 01:00:00    4.666667
26   2011-01-21 02:00:00    7.400000
27   2011-01-21 03:00:00    2.470588
28   2011-01-21 04:00:00    2.470588
29   2011-01-21 05:00:00    2.285714
...                  ...         ...
6463 2012-12-30 18:00:00  145.631579
6464 2012-12-30 19:00:00  143.264706
6465 2012-12-30 20:00:00   95.173913
6466 2012-12-30 21:00:00  129.000000
6467 2012-12-30 22:00:00   77.500000
6468 2012-12-30 23:00:00  108.227273
6469 2012-12-31 00:00:00   36.975610
6470 2012-12-31 01:00:00   17.844444
6471 2012-12-31 02:00:00    9.978723
6472 2012-12-31 03:00:00    6.581818
6473 2012-12-31 04:00:00    6.581818
6474 2012-12-31 05:00:00   35.181818
6475 2012-12-31 06:00:00  117.833333
6476 2012-12-31 07:00:00  265.866667
6477 2012-12-31 08:00:00  490.733333
6478 2012-12-31 09:00:00  227.222222
6479 2012-12-31 10:00:00  112.137255
6480 2012-12-31 11:00:00  112.137255
6481 2012-12-31 12:00:00  112.137255
6482 2012-12-31 13:00:00  112.137255
6483 2012-12-31 14:00:00  112.137255
6484 2012-12-31 15:00:00  112.137255
6485 2012-12-31 16:00:00  112.137255
6486 2012-12-31 17:00:00  286.941176
6487 2012-12-31 18:00:00  286.941176
6488 2012-12-31 19:00:00  181.037037
6489 2012-12-31 20:00:00  181.037037
6490 2012-12-31 21:00:00  163.250000
6491 2012-12-31 22:00:00  109.500000
6492 2012-12-31 23:00:00   87.600000

[6493 rows x 2 columns]